variables:
  # GIT_CLEAN_FLAGS: none # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4154
  GIT_CLONE_PATH: $CI_BUILDS_DIR/isbd-library # https://stackoverflow.com/questions/64089704/gitlab-runner-change-builds-dir

# ! Is important to allow CI_JOB_TOKEN in the private submodules referenced from this project: 
# https://docs.gitlab.com/ee/ci/jobs/ci_job_token.html#add-a-project-to-the-inbound-job-token-scope-allowlist

stages:
  - test

test-job:
  stage: test
  script:
    - source ~/zephyrproject/.venv/bin/activate
    - source ~/zephyrproject/zephyr/zephyr-env.sh
    - twister -vv -T tests/zuart -W
  environment:
    name: production
  tags:
    - isbd-library
  only:
    - main
